export type GameTypes =
  | 'strategy'
  | 'card'
  | 'dice'
  | 'party'
  | 'family'
  | 'trivia'
  | 'cooperative'
  | 'competitive'
  | 'abstract'
  | 'puzzle'
  | 'adventure'
  | 'rpg'
  | 'economy'
  | 'wargame'
  | 'dexterity'
  | 'social_deduction'
